sudo: required
language: node_js
node_js:
  - "node"
  - "10"
install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - type yarn
  - ls -l /usr/bin/yarn && /usr/bin/yarn --version
  - /usr/bin/yarn global add lerna
cache:
  yarn: true
  directories:
    - node_modules
script:
  - /usr/bin/yarn test
  - /usr/bin/yarn lint
